// Mocks generated by Mockito 5.4.6 from annotations
// in vibe_app/test/unit/services/profile_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:vibe_app/features/profile/models/user_model.dart' as _i4;
import 'package:vibe_app/features/profile/services/profile_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i2.ProfileService {
  MockProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserModel?> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i3.Future<_i4.UserModel?>.value(),
          )
          as _i3.Future<_i4.UserModel?>);

  @override
  _i3.Future<_i4.UserModel?> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i3.Future<_i4.UserModel?>.value(),
          )
          as _i3.Future<_i4.UserModel?>);

  @override
  _i3.Future<void> createProfile({
    required String? name,
    required int? age,
    required _i5.File? profilePhoto,
    required String? aboutMe,
    required bool? ageConfirmed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [], {
              #name: name,
              #age: age,
              #profilePhoto: profilePhoto,
              #aboutMe: aboutMe,
              #ageConfirmed: ageConfirmed,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile({
    int? age,
    _i5.File? newProfilePhoto,
    String? aboutMe,
    String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #age: age,
              #newProfilePhoto: newProfilePhoto,
              #aboutMe: aboutMe,
              #username: username,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> uploadProfilePhoto(String? userId, _i5.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [userId, photo]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#uploadProfilePhoto, [userId, photo]),
              ),
            ),
          )
          as _i3.Future<String>);
}
